[General]
bEnableMod = 1

[Stats]
; Seviye farkı başına eklenecek taban değerler (Bu değerler Sınıf çarpanlarıyla çarpılır)
; Base values added per level difference (These are multiplied by Class Multipliers)
fHealthGainPerLevel = 10.0
fMagickaGainPerLevel = 10.0
fStaminaGainPerLevel = 10.0

[Boss]
; Boss ve Ejderhalar için özel çarpan
; Special multiplier for Bosses and Dragons
fBossMultiplier = 1.5

[Resistance]
; Seviye farkı başına Zırh ve Büyü direnci artışı
; Armor and Magic Resistance gain per level difference
fDamageResistPerLevel = 1.0
fMagicResistPerLevel = 1.0

[Damage]
; Seviye farkı başına Hasar artış çarpanları
; Damage multipliers per level difference
fAttackDamageMultPerLevel = 0.05
fSpellPowerModPerLevel = 0.05

[Randomness]
; NPC'lere uygulanan statlar bu iki değer arasında rastgele çarpılır
; Stats applied to NPCs are randomized between these two values
fRandomMin = 0.8
fRandomMax = 1.2

[Tier]
; Karakterinizin her 10 seviyesinde bir NPC'lere eklenecek katlanarak artan bonus çarpan
; The compounding bonus multiplier added to NPCs for every 10 levels of your character
fTierMultiplierPer10Levels = 0.10

[Toggles]
bEnableBanditsAndHumanoids = 1
bEnableAnimals = 1
bEnableMonsters = 1
bEnableUndead = 1
bEnableAutomatons = 1
bEnableDragons = 1
bEnableBosses = 1

[Nerf]
bEnableHighLevelNerf = 1
fNerfDamagePerLevel = 0.03
fNerfArmorPerLevel = 2.0
fMaxNerfLimit = 0.50
